### PR TITLE
[fix issue #256] handle empty YAML files

### LINKED ISSUE #256: spruce cannot merge 2 files, if one of them is empty and/or fully commented out
Test case:

1. File A.yml with empty contents an/or comments-only
2. File B.yml with YAML data

**Actual Result**: A.yml: Root of YAML document is not a hash/map: type assertion to map[interface]interface{} failed

**Expected Result**: A.yml will be handled as empty map.

This is important to handle, because if tool is used for merging different parts of config, it's generally valid scenario when one part will be commented out.

### PR DESCRIPTION
**Pull request by VasylTretiakov**
If the YAML file is [effectively] empty (i.e. does not contain the root hash/map), create an empty hash/map and display a message in debug instead of exiting with error. Fixes #256

### CODE REVIEW

File: cmd/spruce/main.go [hunk 1]
```diff
@@ -235,7 +235,8 @@ func parseYAML(data []byte) (map[interface{}]interface{}, error) {
 		if _, arrayErr := y.Array(); arrayErr == nil {
 			return nil, RootIsArrayError{msg: ansi.Sprintf("@R{Root of YAML document is not a hash/map}: %s\n", err)}
 		}
-		return nil, ansi.Errorf("@R{Root of YAML document is not a hash/map}: %s\n", err.Error())
+		ansi.Errorf("@R{Root of YAML document is not a hash/map, using empty map instead.}\n")
+		doc := make(map[interface{}]interface{})
```
Comment (geofffranks) [inline cmd/spruce/main.go:239]: Can this be done in a way where it only makes an empty doc if the root document is completely empty? 

Also, the call to ansi.Errorf() here does not dow hat you're expecting. it generates and returns a golang error struct, but since it isn't saved to a variable, the error goes nowhere. The `:=` on 239 also re-initializes `doc` in a lower scope, and the code fails to compile. You probably want `=` instead.

I'm going to add some tests on the master branch to make testing this change easier if you want to pull those changes in

Comment (VasylTretiakov) [reply cmd/spruce/main.go:239]: 1. I would agree that handling only empty docs in this way would be preferred, but I have trouble defining what an empty doc is. E.g. _bosh-cli runtime-config_ seems to return a newline when bosh director has no runtime config. If so, we could try to handle only completely empty docs and docs with newline this way (though I am not sure other tools would work similar to bosh-cli when returning no meaningful content). Or we can try raising an issue with bosh-cli to claim they should return nothing in stdout if there is no meaningful content to return.
2. I am sorry, I have to admit my main intention was to start the discussion. Of course, once we agree on the best approach I would be happy to use the tests you are suggesting to put in place and to nature this PR.

Comment (geofffranks) [reply cmd/spruce/main.go:239]: No worries, I appreciate the conversation!

For empty yaml files, I would define that as anything a yaml parser returns as a nil object. So probably a file with nothing, a file with only white space, or a file with only yaml’s null keywords in it?

Comment (VasylTretiakov) [reply cmd/spruce/main.go:239]: Thanks, that sounds like a wonderful technical empty doc criterion. Let me go over the code with this definition in mind to see what would be the best way to implement it.

**Comment by VasylTretiakov** [comment]
@geofffranks , thanks for the updated tests. Please review the latest code changes.
