### PR TITLE
Key merge no longer panics if target keys' value is sequence or hash

### LINKED ISSUE #172: Panic during merges
When merging values, if we have an array, with a map object, whose `name` key is not a string, we get a panic:

```
array-of-maps:
- name: { subkey1, subkey2: val2 }
```

results in:

```
panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
panic(0x462720, 0xc8200f6ab0)
    /usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/geofffranks/spruce.(*Merger).mergeArrayByKey(0xc8200dbd70, 0x743ab0, 0x0, 0x0, 0xc8200f6a80, 0x1, 0x1, 0xc8200117a0, 0xf, 0x4eac38, ...)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:334 +0x31c
github.com/geofffranks/spruce.(*Merger).mergeArrayDefault(0xc8200dbd70, 0x743ab0, 0x0, 0x0, 0xc8200f6a80, 0x1, 0x1, 0xc8200117a0, 0xf, 0x0, ...)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:287 +0x303
github.com/geofffranks/spruce.(*Merger).mergeArray(0xc8200dbd70, 0x743ab0, 0x0, 0x0, 0xc8200117c0, 0x1, 0x1, 0xc8200117a0, 0xf, 0x0, ...)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:201 +0x143d
github.com/geofffranks/spruce.(*Merger).mergeObj(0xc8200dbd70, 0x0, 0x0, 0x39e800, 0xc8200cae20, 0xc8200117a0, 0xf, 0x0, 0x0)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:143 +0x7fb
github.com/geofffranks/spruce.(*Merger).mergeMap(0xc8200dbd70, 0xc82000bb30, 0xc82000bc50, 0x4e7058, 0x1)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:95 +0x880
github.com/geofffranks/spruce.(*Merger).Merge(0xc8200dbd70, 0xc82000bb30, 0xc82000bc50, 0x0, 0x0)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/merge.go:78 +0x5a
main.mergeAllDocs(0xc82000bb30, 0xc820011500, 0x1, 0x1, 0x0, 0x0)
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/cmd/spruce/main.go:194 +0x6bf
main.main()
    /Users/gfranks/code/go/src/github.com/geofffranks/spruce/cmd/spruce/main.go:96 +0x9cf
```

This also occurs in situations where you override the merge-key, like this:

```
array-of-maps:
- (( merge on mergekey ))
- mergekey: { subkey1, subkey2: val2 }
```

### PR DESCRIPTION
**Pull request by thomasmmitchell**
Fixes #172
If implicit merge got us here, a warning is given, and it falls back to an inline strategy.
If explicitly stated to merge, an error is given.
A new WarningError object with a regulated warning output was made to facilitate this. The operator warnings were updated to use this.
Warnings can be silenced from the code, so no more warnings from passing tests!
Tests were added.
Log library scope changes to facilitate testing with new warning system.

### CODE REVIEW

File: cmd/spruce/main_test.go [hunk 1]
```diff
@@ -162,7 +162,8 @@ func TestMain(t *testing.T) {
 			stdout = fmt.Sprintf(format, args...)
 		}
 		var stderr string
-		printfStdErr = func(format string, args ...interface{}) {
+		//Edit log stderr function
+		PrintfStdErr = func(format string, args ...interface{}) {
```
Comment (geofffranks) [inline cmd/spruce/main_test.go]: I'm confused why you did this instead of editing the existing printfStdErr function, which was put in place to do tests just like this

File: merge.go [hunk 2]
```diff
@@ -282,12 +282,23 @@ func (m *Merger) mergeArray(orig []interface{}, n []interface{}, node string) []
...
 	}
 
+	//Warn the user about any unintuitive behavior that may have gotten us here.
+	if warning, isWarning := err.(WarningError); isWarning && warning.HasContext(eContextDefaultMerge) {
+		mergeStratStr := "inline"
+		if m.AppendByDefault {
+			mergeStratStr = "append"
+		}
+		warning.SetWarning(ansi.Sprintf("%s\n  @Y{Falling back to %s merge strategy}", warning.Error(), mergeStratStr))
+		warning.Warn()
```
Comment (geofffranks) [inline merge.go]: Why not just warn with a string, and each new warning prints on a new line?

File: merge.go [hunk 3]
```diff
@@ -493,15 +504,23 @@ func canKeyMergeArray(disp string, array []interface{}, node string, key string)
...
 		obj := o.(map[interface{}]interface{})
 		if _, ok := obj[key]; !ok {
-			return ansi.Errorf("@m{%s.%d}: @R{%s object does not contain the key} @c{'%s'}@R{ - cannot merge}", node, i, disp, key)
+			return ansi.Errorf("@m{%s.%d}: @R{%s object does not contain the key} @c{'%s'}@R{ - cannot merge by key}", node, i, disp, key)
+		}
+
+		//Verify that the target key has a hashable value (i.e. a value that is not itself a hash or sequence)
+		targetValue := obj[key]
+		_, isMap := targetValue.(map[interface{}]interface{})
+		_, isSlice := targetValue.([]interface{})
```
Comment (geofffranks) [inline merge.go]: How are numerics/booleans handled? If we try to merge where `name: true` or `name: 1.0`, do we still get panics?

File: cmd/spruce/main_test.go (hunk 1 above)
Comment (thomasmmitchell) [inline cmd/spruce/main_test.go]: Because the warnings print out through the log library, which, in order to be tested, needs to have a hook that we can insert our string into. The warnings, because they're in the spruce package, can't use that function, lest we dependency cycle.

File: merge.go (hunk 3 above)
Comment (thomasmmitchell) [inline merge.go]: Did we ever?

File: cmd/spruce/main_test.go (hunk 1 above)
Comment (geofffranks) [inline cmd/spruce/main_test.go]: But this is code scoped to just the `main` package, and isn't referencing the log package.. I guess if importing was an issue, why not just rename `var printfStdErr` to `var PrintfStdErr`, instead of make a new function that did the same thing, wrapped by the original?

File: merge.go (hunk 3 above)
Comment (geofffranks) [inline merge.go]: Tried some stuff in play.spruce.cf just now. Looks like boolean/numerics/nils are handled properly and no panics.

File: cmd/spruce/main_test.go (hunk 1 above)
Comment (thomasmmitchell) [inline cmd/spruce/main_test.go]: The tests validate that what went to stderr is what's expected. In order to test it, we need a hook to capture stderr in our tests. That's the string above. The problem is that we actually have two different spots in the code where printing to stderr is done. Hard errors propagate back up to main, and therefore get printed using the printfStdErr in main, which has been testable. Things that don't stop everything and propagate up to main use the log libraries printf function indirectly (DEBUG, TRACE, and now Warn()... we just weren't testing debug and trace before). 

Both the log and main versions of the function were doing the same thing. It's just that the log one was private and therefore not usable for testing. So I made it public, and rerouted the main one through the log one.

Even cleaner might be to update all the calls to printfstderr in main to use the log library version and get rid of the one in main. Log library is for printing out the logs... why aren't we using it everywhere?

File: merge.go (hunk 3 above)
Comment (thomasmmitchell) [inline merge.go]: ints never caused an issue
http://play.spruce.cf/#9e148fac01c29775d39210f2b0285d36

booleans, while silly and limited for this purpose... don't cause errors either
http://play.spruce.cf/#d46ae4548571960d823b8fe095d959a2

Comment (thomasmmitchell) [inline merge.go]: Example with floats if you want
http://play.spruce.cf/#e0b626f98659f4af798715304caf0199

File: merge.go (hunk 2 above)
Comment (thomasmmitchell) [inline merge.go]: Can you give an example?

Comment (geofffranks) [inline merge.go]: Seems weird to receive an error that you then have to set the message value on, and then log. Why not just call something like 
```
if err != nil {
    mergeStratStr := "inline"
    if m.AppendByDefault {
        mergeStratStr = "append"
    }
    log.Warn("Could not merge by key: %s\n@y{Falling back to %s merge strategy}", err, mergeStratStr)
}
```

File: cmd/spruce/main_test.go (hunk 1 above)
Comment (geofffranks) [inline cmd/spruce/main_test.go]: Probably didn't exist originally. Let's update everything to just use log.PrintStdErr

File: merge.go (hunk 2 above)
Comment (thomasmmitchell) [inline merge.go]: I just wanted to append an extra part of the message to the given error, but I do like the idea of an optional arg to Warn to do it all in one call.

**Comment by thomasmmitchell** [comment]
I've addressed what's here so far. Anything else?
